### ISSUE TITLE
在最新Steam Families Beta已失效

### ISSUE THREAD

**Issue by Guailoudou** [emtry/wuhu#13]
在最新Steam Families Beta已失效，可以在对方开始游戏后进入，但3min后会被踢出

**Comment by ehgen0ng** [comment]
等待更新

**Comment by ehgen0ng** [comment]
wuhu_beta.bat
你试试吧，我没Steam Families Beta

**Comment by Guailoudou** [comment]
经黑神话悟空测试，beta版无效，启动会提示steam账户无此游戏，请检查所有权，点击确认后steam闪退，之后启动游戏进程会卡住，关闭游戏steam会闪退
