### ISSUE TITLE
举手提问

### ISSUE THREAD

**Issue by anatoliux2233** [emtry/wuhu#15]
Steam主程序和库不在同一个盘，请问也是解压到Steam根目录而不是库目录吗？我想解锁黑神话的豪华版dlc和预购奖励，但好像没有起效

**Comment by ehgen0ng** [comment]
Steam根目录，本体ID和DLC ID都加试试

**Comment by anatoliux2233** [comment]
哇好快，感谢解答

**Comment by anatoliux2233** [comment]
嗯，还是不行[笑哭]

**Comment by ehgen0ng** [comment]
那DLC应该是单独下载的，要找个有豪华版的号下载DLC才能解

**Comment by ehgen0ng** [comment]
有豪华版的家庭库里拉了个小号测试，实测小号能解豪华版
