### ISSUE TITLE
执行wuhu.bat时报错Dllinjector failed to start exe

### ISSUE THREAD

**Issue by ccpp007** [emtry/wuhu#4]
执行wuhu.bat时报错Dllinjector failed to start exe

**Comment by emtry** [comment]
文件夹放错位置
tree
./
steam.exe
wuhu/
           wuhu.bat

**Comment by ehgen0ng** [comment]
文件夹放错位置
tree
./
steam.exe
wuhu/
______wuhu.bat

**Comment by ccpp007** [comment]
我的路径是
C:\Program Files (x86)\Steam\wuhu-master
放到一个新电脑里运行报错的



------------------ 原始邮件 ------------------
发件人: ehgenong ***@***.***&gt;
发送时间: 2022年12月8日 09:23
收件人: emtry/wuhu ***@***.***&gt;
抄送: CC ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [emtry/wuhu] 执行wuhu.bat时报错Dllinjector failed to start exe (Issue #4)





 
文件夹放错位置
 tree
 ./
 steam.exe
 wuhu/
 ______wuhu.bat

**Comment by ccpp007** [comment]
tree./steam.exewuhu/______wuhu.bat
没看懂这是什么路径


我这边路径是
C:\Program Files (x86)\Steam\wuhu-master
在一台新电脑运行报错的

**Comment by ccpp007** [comment]
tree./steam.exewuhu/______wuhu.bat
没看懂这是什么路径


我这边路径是
C:\Program Files (x86)\Steam\wuhu-master
在一台新电脑运行报错的
